### ISSUE TITLE
problem of usage

### ISSUE THREAD

**Issue by rosyapril** [Toni-SM/omni.add_on.ros_bridge_ui#1]
Hi Toni,

I downloaded usd.shcema.add_on and this extension and enable it as you stated. I want to test the compressed function. However, when I clicked "the enabled", no rostopic has shown as native ROS_Camera. Do you have any idea about how to fix it?

I am using Isaac Sim 2021.1.0. Thanks!

**Comment by Toni-SM** [comment]
Hi @rosyapril.

In the NVIDIA forum (https://forums.developer.nvidia.com/t/external-extensions-ros-bridge-ui-add-on/182264/3?u=toni.sm) you can find the answer and the extension that is in charge of providing the functionality behind the topic. 

Kindly...
