### ISSUE TITLE
JointTrajectoryFollower not working

### ISSUE THREAD

**Issue by Ubb90** [Toni-SM/omni.add_on.ros_bridge_ui#2]
Hello, 

I've installed the extension and it's dependencies and created a follower server, however `ros2 action list` doesn't return anything.
From what i've understood you need the ros_bridge extension you've also developed, which doesn't load because I am using ros2. Is there something I'm missing or have you not yet release the ros2_bridge ?

**Comment by Toni-SM** [comment]
Hi @09ubberboy90 

I have not implemented the extensions for ROS 2 yet...
It is on my working list

**Comment by Ubb90** [comment]
Thank you.
Is there anything i can help you with ?
